### ISSUE TITLE
特殊字元保留

### ISSUE THREAD

**Issue by coldsheepTW** [jwlin/ptt-web-crawler#13]
抱歉python新手
由於需要爬ptt資料所以找到這好用的工具

用的過程中發現程式自動把全形空白、換行等
都替換掉了
想請教有沒有選項可以關掉filter
或是python程式中哪邊可以如何修改？

感謝

**Comment by jwlin** [comment]
crawler.py 的 122-124 行註解掉即可
https://github.com/jwlin/ptt-web-crawler/blob/master/PttWebCrawler/crawler.py#L122

**Comment by coldsheepTW** [comment]
thanks!
