### ISSUE TITLE
Add pyOpenSSL to requirements.txt?

### ISSUE THREAD

**Issue by bearnun** [jwlin/ptt-web-crawler#17]
tldr; Does pyOpenSSL need to be added to requirements.txt or am I missing something?

Tests were failing/couldn't run the crawler when I cloned this repo, but after referring to (https://stackoverflow.com/questions/35405092/sslerror-sslv3-alert-handshake-failure) I did a 'pip install pyOpenSSL' and this fixed the web crawler work/got tests passing.

**Comment by jwlin** [comment]
I don't have this issue, but it does't hurt adding this package. Thanks.
