### ISSUE TITLE
很在意json格式裡的命名

### ISSUE THREAD

**Issue by t42ji2ji** [jwlin/ptt-web-crawler#19]
message_conut 是不是打錯 message_count?

**Comment by jwlin** [comment]
Fixed. Thanks. https://github.com/jwlin/ptt-web-crawler/commit/e319ebc32e0589cb0427b676bf956593e4d1c9dd

**Comment by jwlin** [comment]
Fixed. Thanks. https://github.com/jwlin/ptt-web-crawler/commit/e319ebc32e0589cb0427b676bf956593e4d1c9dd
